name: Deploy demo env

on:
  workflow_dispatch:
    inputs:
      DEVCENTER_NAME:
        description: 'DevCenter Name'     
        required: true
        default: 'devcenterdemolgm'
      PROJECT_NAME:
        description: 'Project Name' 
        required: true
        default: 'DevProject'
      RESOURCE_GROUP:
        description: 'Resource Group' 
        required: true
        default: 'rg-demo-ade'
      LOCATION:
        description: 'Location' 
        required: true
        default: 'westeurope'
      KV_NAME:
        description: 'Keyvault name' 
        required: true
        default: 'kv-demoadelgm'
      PAT_TOKEN:
          description: 'PAT allowing to access your Github Repo' 
          required: false
jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
          
      - name: AZ Login
        run: az login --service-principal -u ${{ vars.AZ_LOGIN }} -p ${{ secrets.AZ_PASSWORD }} --tenant ${{ vars.AZ_TENANT }}
        
      - name: Prerequisites
        run: |
          # install extension silently
          az config set extension.use_dynamic_install=yes_without_prompt

          # install extension
          az extension add --name devcenter --allow-preview true
      - name: Deploy
        run: |
          RED="\e[31m"
          GREEN="\e[32m"
          ORANGE="\e[95m"
          ENDCOLOR="\e[0m" 
         
          # create RG
          echo "Creating RG"
          az group create -n "${{ github.event.inputs.RESOURCE_GROUP }}" -l ${{ github.event.inputs.LOCATION }} -o none
          printf $"${GREEN}\u2714 Success ${ENDCOLOR}\n\n"

          # create keyvault & inject PAT as secret
          if [ $(az keyvault check-name --name "${{ github.event.inputs.KV_NAME }}" --query nameAvailable -o tsv) = false ]; then
            echo 'KV already exist. Trying purge'
            az keyvault purge --name "${{ github.event.inputs.KV_NAME }}"
          fi

          echo "Creating keyvault"
          if [ $(az keyvault list-deleted --query "[?contains(name, '${{ github.event.inputs.KV_NAME }}')].name" -o tsv) = '${{ github.event.inputs.KV_NAME }}' ]; then
            echo 'KV already exist. Trying to purge it'
            az keyvault purge --name "${{ github.event.inputs.KV_NAME }}"
          fi
          az keyvault create -n "${{ github.event.inputs.KV_NAME }}" -l ${{ github.event.inputs.LOCATION }} -g "${{ github.event.inputs.RESOURCE_GROUP }}"  -o none
          export GHPAT="${{ github.event.inputs.PAT_TOKEN }}"
          if [ -z "$GHPAT" ]
          then
              echo "create secret using PAT given in secrets"
              az keyvault secret set --vault-name "${{ github.event.inputs.KV_NAME }}" --name GHPAT --value "${{ secrets.PAT_TOKEN }}" -o none
          else
             echo "create secret using PAT given in input"
              az keyvault secret set --vault-name "${{ github.event.inputs.KV_NAME }}" --name GHPAT --value "${{ github.event.inputs.PAT_TOKEN }}"  -o none
          fi
          printf $"${GREEN}\u2714 Success ${ENDCOLOR}\n\n"

          # create dev environnement
          echo "Creating dev center"
          az devcenter admin devcenter create --location "${{ github.event.inputs.LOCATION }}" --name "${{ github.event.inputs.DEVCENTER_NAME }}" --resource-group "${{ github.event.inputs.RESOURCE_GROUP }}" -o none
          printf $"${GREEN}\u2714 Success ${ENDCOLOR}\n\n"

          # enable system identity on DevCenter
          echo "Enabling managed identity"
          az devcenter admin devcenter update -n "${{ github.event.inputs.DEVCENTER_NAME }}" --identity-type SystemAssigned --resource-group "${{ github.event.inputs.RESOURCE_GROUP }}" -o none
          printf $"${GREEN}\u2714 Success ${ENDCOLOR}\n\n"

          # retrieving DevCenter identity
          echo "Retrieving managed identity"
          OID=$(az ad sp list --display-name "${{ github.event.inputs.DEVCENTER_NAME }}" --query [].id -o tsv)
          printf "${ORANGE}$OID${ENDCOLOR}\n"
          sleep 30 # wait for replication
          echo -e "Creating KV policy"
          az keyvault set-policy -n "${{ github.event.inputs.KV_NAME }}" --secret-permissions get --object-id $OID -g ${{ github.event.inputs.RESOURCE_GROUP }} -o none
          printf $"${GREEN}\u2714 Success ${ENDCOLOR}\n\n"

          # retrieve DevCenterId
          DEVCENTER_ID=$(az devcenter admin devcenter show --name "${{ github.event.inputs.DEVCENTER_NAME }}" --resource-group "${{ github.event.inputs.RESOURCE_GROUP }}" --query=id -o tsv)

          # Create environment types
          echo "Creating environments"
          az devcenter admin environment-type create --dev-center-name "${{ github.event.inputs.DEVCENTER_NAME }}" --name "PROD" --resource-group "${{ github.event.inputs.RESOURCE_GROUP }}" -o none
          az devcenter admin environment-type create --dev-center-name "${{ github.event.inputs.DEVCENTER_NAME }}" --name "TEST" --resource-group "${{ github.event.inputs.RESOURCE_GROUP }}" -o none
          az devcenter admin environment-type create --dev-center-name "${{ github.event.inputs.DEVCENTER_NAME }}" --name "DEV" --resource-group "${{ github.event.inputs.RESOURCE_GROUP }}" -o none
          printf $"${GREEN}\u2714 Success ${ENDCOLOR}\n\n"

          # create a project
          echo "Creating projects"
          az devcenter admin project create --location "${{ github.event.inputs.LOCATION }}" --description "This is my first project." --dev-center-id "$DEVCENTER_ID" --name "DevProject" --resource-group "${{ github.event.inputs.RESOURCE_GROUP }}" --max-dev-boxes-per-user "3" -o none
          printf $"${GREEN}\u2714 Success ${ENDCOLOR}\n\n"

          # create a DevBox
          echo "Creating dev box"
          az devcenter admin devbox-definition create --location "${{ github.event.inputs.LOCATION }}" --image-reference id="/subscriptions/${{ vars.SUBSCRIPTION_ID }}/resourceGroups/${{ github.event.inputs.RESOURCE_GROUP }}/providers/Microsoft.DevCenter/devcenters/${{ github.event.inputs.DEVCENTER_NAME }}/galleries/default/images/microsoftvisualstudio_visualstudioplustools_vs-2022-ent-general-win11-m365-gen2" --os-storage-type "ssd_256gb" --sku name="general_i_8c32gb256ssd_v2" --name "WebDevBox" --dev-center-name "${{ github.event.inputs.DEVCENTER_NAME }}" --resource-group "${{ github.event.inputs.RESOURCE_GROUP }}" -o none
          az devcenter admin devbox-definition create --location "${{ github.event.inputs.LOCATION }}" --image-reference id="/subscriptions/${{ vars.SUBSCRIPTION_ID }}/resourceGroups/${{ github.event.inputs.RESOURCE_GROUP }}/providers/Microsoft.DevCenter/devcenters/${{ github.event.inputs.DEVCENTER_NAME }}/galleries/default/images/microsoftvisualstudio_visualstudioplustools_vs-2022-ent-general-win11-m365-gen2" --os-storage-type "ssd_512gb" --sku name="general_i_32c128gb512ssd_v2" --name "SuperPowerfulDevBox" --dev-center-name "${{ github.event.inputs.DEVCENTER_NAME }}" --resource-group "${{ github.event.inputs.RESOURCE_GROUP }}" -o none
          printf $"${GREEN}\u2714 Success ${ENDCOLOR}\n\n"

          # create a catalog
          echo "Creating catalog"
          SECRETID=$(az keyvault secret show --vault-name ${{ github.event.inputs.KV_NAME }} --name GHPAT --query id -o tsv)
          printf "${ORANGE} $SECRETID ${ENDCOLOR}\n"
          REPO_URL="https://github.com/lgmorand/azure-ade-devbox.git"
          az devcenter admin catalog create --git-hub path="/Environments" branch="main" secret-identifier=$SECRETID uri=$REPO_URL -n "EnvCatalog" -d "${{ github.event.inputs.DEVCENTER_NAME }}" -g ${{ github.event.inputs.RESOURCE_GROUP }} -o none
          REPO_URL="https://github.com/microsoft/devcenter-catalog.git"
          az devcenter admin catalog create --git-hub path="/Tasks" branch="main" secret-identifier=$SECRETID uri=$REPO_URL -n "QuickStart" -d "${{ github.event.inputs.DEVCENTER_NAME }}" -g ${{ github.event.inputs.RESOURCE_GROUP }} -o none
          printf $"${GREEN}\u2714 Success ${ENDCOLOR}\n\n"

          # creating pools
          echo "Creating pools"
          az devcenter admin pool create --location "${{ github.event.inputs.LOCATION }}" --devbox-definition-name "WebDevBox" --pool-name "DevPool" --project-name "DevProject" --resource-group "${{ github.event.inputs.RESOURCE_GROUP }}" --local-administrator "Enabled" --virtual-network-type "Managed" --managed-virtual-network-regions "westeurope" -o none
          az devcenter admin pool create --location "${{ github.event.inputs.LOCATION }}" --devbox-definition-name "SuperPowerfulDevBox" --pool-name "DevPoolPowerFull" --project-name "DevProject" --resource-group "${{ github.event.inputs.RESOURCE_GROUP }}" --local-administrator "Enabled" --virtual-network-type "Managed" --managed-virtual-network-regions "westeurope" -o none
          printf $"${GREEN}\u2714 Success ${ENDCOLOR}\n\n"